const action_types = {
    IRC_CREATE_CONNECTION: 'IRC_CREATE_CONNECTION',
    IRC_RECEIVE_ANY: 'IRC_RECEIVE_ANY',
    IRC_RECEIVE_MESSAGE: 'IRC_RECEIVE_MESSAGE',
    IRC_RECEIVE_JOIN: 'IRC_RECEIVE_JOIN'
};

export default action_types;